using Backend.Domain.Entities.Agents;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Backend.Domain.Enums.Occupations
{
    public class Occupations
    {
        public static List<AgentOccupation> OccupationList = new List<AgentOccupation>()
        {
            new AgentOccupation(992110, "Balanceador"),
            new AgentOccupation(992115, "Borracheiro"),
            new AgentOccupation(992120, "Lavador de peças"),
            new AgentOccupation(992205, "Encarregado geral de operações de conservação de vias permanentes (exceto trilhos)"),
            new AgentOccupation(992210, "Encarregado de equipe de conservação de vias permanentes (exceto trilhos)"),
            new AgentOccupation(992215, "Operador de ceifadeira na conservação de vias permanentes"),
            new AgentOccupation(992220, "Pedreiro de conservação de vias permanentes (exceto trilhos)"),
            new AgentOccupation(992225, "Auxiliar geral de conservação de vias permanentes (exceto trilhos)"),
            new AgentOccupation(992230, "Jardineiro"),
            new AgentOccupation(992235, "Faxineiro"),
            new AgentOccupation(992240, "Zelador"),
            new AgentOccupation(992305, "Vigia"),
            new AgentOccupation(992310, "Porteiro"),
            new AgentOccupation(992315, "Ascensorista"),
            new AgentOccupation(992320, "Carregador de malas"),
            new AgentOccupation(992325, "Manobrista"),
            new AgentOccupation(992330, "Guardião de piscina"),
            new AgentOccupation(992405, "Encarregado de serviços gerais"),
            new AgentOccupation(992410, "Auxiliar de serviços gerais"),
            new AgentOccupation(992415, "Copeiro"),
            new AgentOccupation(992420, "Garçom"),
            new AgentOccupation(992425, "Barman"),
            new AgentOccupation(992430, "Cozinheiro"),
            new AgentOccupation(992435, "Auxiliar de cozinha"),
            new AgentOccupation(992440, "Auxiliar de limpeza"),
            new AgentOccupation(992445, "Lavador de pratos"),
            new AgentOccupation(992450, "Repositor de mercadorias"),
            new AgentOccupation(992455, "Embalador"),
            new AgentOccupation(992460, "Separador de mercadorias"),
            new AgentOccupation(992465, "Conferente de mercadorias"),
            new AgentOccupation(992470, "Operador de empilhadeira"),
            new AgentOccupation(992475, "Auxiliar de almoxarifado"),
            new AgentOccupation(992480, "Auxiliar de expedição"),
            new AgentOccupation(992485, "Controlador de acesso"),
            new AgentOccupation(992490, "Recepcionista"),
            new AgentOccupation(992495, "Telefonista"),
            new AgentOccupation(992500, "Atendente"),
            new AgentOccupation(992505, "Operador de telemarketing"),
            new AgentOccupation(992510, "Auxiliar administrativo"),
            new AgentOccupation(992515, "Assistente administrativo"),
            new AgentOccupation(992520, "Secretária"),
            new AgentOccupation(992525, "Analista de atendimento"),
            new AgentOccupation(992530, "Motorista"),
            new AgentOccupation(992535, "Motoboy"),
            new AgentOccupation(992540, "Entregador"),
            new AgentOccupation(992545, "Cobrador de transporte coletivo"),
            new AgentOccupation(992550, "Auxiliar de transporte"),
            new AgentOccupation(992555, "Frentista"),
            new AgentOccupation(992560, "Operador de caixa"),
            new AgentOccupation(992565, "Atendente de lanchonete"),
            new AgentOccupation(992570, "Balconista"),
            new AgentOccupation(992575, "Auxiliar de farmácia"),
            new AgentOccupation(992580, "Farmacêutico"),
            new AgentOccupation(992585, "Técnico de enfermagem"),
            new AgentOccupation(992590, "Auxiliar de enfermagem"),
            new AgentOccupation(992595, "Recepcionista de clínica"),
            new AgentOccupation(992600, "Auxiliar de laboratório"),
            new AgentOccupation(992605, "Técnico de laboratório"),
            new AgentOccupation(992610, "Operador de máquinas"),
            new AgentOccupation(992615, "Técnico de manutenção"),
            new AgentOccupation(992620, "Eletricista"),
            new AgentOccupation(992625, "Encanador"),
            new AgentOccupation(992630, "Carpinteiro"),
            new AgentOccupation(992635, "Pintor"),
            new AgentOccupation(992640, "Marceneiro"),
            new AgentOccupation(992645, "Serralheiro"),
            new AgentOccupation(992650, "Soldador"),
            new AgentOccupation(992655, "Mecânico"),
            new AgentOccupation(992660, "Técnico em eletrônica"),
            new AgentOccupation(992665, "Técnico em telecomunicações"),
            new AgentOccupation(992670, "Técnico de informática"),
            new AgentOccupation(992675, "Programador"),
            new AgentOccupation(992680, "Desenvolvedor de software"),
            new AgentOccupation(992685, "Analista de sistemas"),
            new AgentOccupation(992690, "Engenheiro de software"),
            new AgentOccupation(992695, "Engenheiro civil"),
            new AgentOccupation(992700, "Engenheiro mecânico"),
            new AgentOccupation(992705, "Engenheiro elétrico"),
            new AgentOccupation(992710, "Engenheiro eletrônico"),
            new AgentOccupation(992715, "Engenheiro químico"),
            new AgentOccupation(992720, "Engenheiro de produção"),
            new AgentOccupation(992725, "Arquiteto"),
            new AgentOccupation(992730, "Urbanista"),
            new AgentOccupation(992735, "Designer gráfico"),
            new AgentOccupation(992740, "Ilustrador"),
            new AgentOccupation(992745, "Fotógrafo"),
            new AgentOccupation(992750, "Cinegrafista"),
            new AgentOccupation(992755, "Editor de vídeo"),
            new AgentOccupation(992760, "Diretor de arte"),
            new AgentOccupation(992765, "Publicitário"),
            new AgentOccupation(992770, "Jornalista"),
            new AgentOccupation(992775, "Radialista"),
            new AgentOccupation(992780, "Roteirista"),
            new AgentOccupation(992785, "Produtor audiovisual"),
            new AgentOccupation(992790, "Editor de texto"),
            new AgentOccupation(992795, "Revisor de texto"),
            new AgentOccupation(992800, "Tradutor"),
            new AgentOccupation(992805, "Intérprete"),
            new AgentOccupation(992810, "Professor"),
            new AgentOccupation(992815, "Instrutor"),
            new AgentOccupation(992820, "Pedagogo"),
            new AgentOccupation(992825, "Psicopedagogo"),
            new AgentOccupation(992830, "Coordenador pedagógico"),
            new AgentOccupation(992835, "Orientador educacional"),
            new AgentOccupation(992840, "Diretor escolar"),
            new AgentOccupation(992845, "Supervisor de ensino"),
            new AgentOccupation(992850, "Bibliotecário"),
            new AgentOccupation(992855, "Documentalista"),
            new AgentOccupation(992860, "Arquivista"),
            new AgentOccupation(992865, "Historiador"),
            new AgentOccupation(992870, "Geógrafo"),
            new AgentOccupation(992875, "Sociólogo"),
            new AgentOccupation(992880, "Antropólogo"),
            new AgentOccupation(992885, "Filósofo"),
            new AgentOccupation(992890, "Teólogo"),
            new AgentOccupation(992895, "Cientista político"),
            new AgentOccupation(992900, "Economista"),
            new AgentOccupation(992905, "Administrador"),
            new AgentOccupation(992910, "Contador"),
            new AgentOccupation(992915, "Auditor"),
            new AgentOccupation(992920, "Analista financeiro"),
            new AgentOccupation(992925, "Consultor"),
            new AgentOccupation(992930, "Analista de recursos humanos"),
            new AgentOccupation(992935, "Gestor de projetos"),
            new AgentOccupation(992940, "Analista de marketing"),
            new AgentOccupation(992945, "Gestor de negócios"),
            new AgentOccupation(992950, "Especialista em logística"),
            new AgentOccupation(992955, "Gestor ambiental"),
            new AgentOccupation(992960, "Analista de sustentabilidade"),
            new AgentOccupation(992965, "Especialista em responsabilidade social"),
            new AgentOccupation(992970, "Gestor de inovação"),
            new AgentOccupation(992975, "Gestor de tecnologia da informação"),
            new AgentOccupation(992980, "Gestor de segurança da informação"),
            new AgentOccupation(992985, "Especialista em inteligência artificial"),
            new AgentOccupation(992990, "Especialista em big data"),
            new AgentOccupation(992995, "Especialista em ciência de dados"),
            new AgentOccupation(993000, "Pesquisador"),
            new AgentOccupation(993005, "Cientista"),
            new AgentOccupation(993010, "Biólogo"),
            new AgentOccupation(993015, "Químico"),
            new AgentOccupation(993020, "Físico"),
            new AgentOccupation(993025, "Matemático"),
            new AgentOccupation(993030, "Estatístico"),
            new AgentOccupation(993035, "Geólogo"),
            new AgentOccupation(993040, "Oceanógrafo"),
            new AgentOccupation(993045, "Meteorologista"),
            new AgentOccupation(993050, "Astrônomo"),
            new AgentOccupation(993055, "Ecólogo"),
            new AgentOccupation(993060, "Engenheiro ambiental"),
            new AgentOccupation(993065, "Engenheiro florestal"),
            new AgentOccupation(993070, "Agrônomo"),
            new AgentOccupation(993075, "Zootecnista"),
            new AgentOccupation(993080, "Veterinário"),
            new AgentOccupation(993085, "Técnico agrícola"),
            new AgentOccupation(993090, "Pesquisador agropecuário"),
            new AgentOccupation(993095, "Pesquisador florestal"),
            new AgentOccupation(993100, "Especialista em biotecnologia"),
            new AgentOccupation(993105, "Especialista em nanotecnologia"),
            new AgentOccupation(993110, "Especialista em robótica"),
            new AgentOccupation(993115, "Especialista em mecatrônica"),
            new AgentOccupation(993120, "Desenvolvedor de jogos"),
            new AgentOccupation(993125, "Analista de redes"),
            new AgentOccupation(993130, "Administrador de sistemas"),
            new AgentOccupation(993135, "Administrador de banco de dados"),
            new AgentOccupation(993140, "Especialista em segurança cibernética"),
            new AgentOccupation(993145, "Gerente de TI"),
            new AgentOccupation(993150, "Engenheiro de dados"),
            new AgentOccupation(993155, "Engenheiro de machine learning"),
            new AgentOccupation(993160, "Engenheiro de DevOps"),
            new AgentOccupation(993165, "Especialista em cloud computing"),
            new AgentOccupation(993170, "Especialista em blockchain"),
            new AgentOccupation(993175, "Especialista em internet das coisas (IoT)"),
            new AgentOccupation(993180, "Consultor de transformação digital"),
            new AgentOccupation(993185, "Especialista em automação industrial"),
            new AgentOccupation(993190, "Engenheiro de controle e automação"),
            new AgentOccupation(993195, "Técnico de manutenção industrial"),
            new AgentOccupation(993200, "Mecânico de manutenção"),
            new AgentOccupation(993205, "Técnico em instrumentação"),
            new AgentOccupation(993210, "Técnico em automação"),
            new AgentOccupation(993215, "Engenheiro de processos"),
            new AgentOccupation(993220, "Especialista em lean manufacturing"),
            new AgentOccupation(993225, "Especialista em gestão da qualidade"),
            new AgentOccupation(993230, "Auditor de qualidade"),
            new AgentOccupation(993235, "Inspetor de qualidade"),
            new AgentOccupation(993240, "Analista de produção"),
            new AgentOccupation(993245, "Supervisor de produção"),
            new AgentOccupation(993250, "Gerente de produção"),
            new AgentOccupation(993255, "Diretor de operações"),
            new AgentOccupation(993260, "Consultor de produtividade"),
            new AgentOccupation(993265, "Especialista em melhoria contínua"),
            new AgentOccupation(993270, "Engenheiro de projetos"),
            new AgentOccupation(993275, "Gerente de projetos"),
            new AgentOccupation(993280, "Coordenador de projetos"),
            new AgentOccupation(993285, "Analista de riscos"),
            new AgentOccupation(993290, "Especialista em compliance"),
            new AgentOccupation(993295, "Gestor de crises"),
            new AgentOccupation(993300, "Consultor de segurança"),
            new AgentOccupation(993305, "Especialista em segurança do trabalho"),
            new AgentOccupation(993310, "Técnico em segurança do trabalho"),
            new AgentOccupation(993315, "Engenheiro de segurança do trabalho"),
            new AgentOccupation(993320, "Médico do trabalho"),
            new AgentOccupation(993325, "Enfermeiro do trabalho"),
            new AgentOccupation(993330, "Fonoaudiólogo"),
            new AgentOccupation(993335, "Fisioterapeuta"),
            new AgentOccupation(993340, "Terapeuta ocupacional"),
            new AgentOccupation(993345, "Psicólogo"),
            new AgentOccupation(993350, "Assistente social"),
            new AgentOccupation(993355, "Nutricionista"),
            new AgentOccupation(993360, "Fonoaudiólogo educacional"),
            new AgentOccupation(993365, "Fisioterapeuta esportivo"),
            new AgentOccupation(993370, "Terapeuta ocupacional clínico"),
            new AgentOccupation(993375, "Psicólogo clínico"),
            new AgentOccupation(993380, "Assistente social clínico"),
            new AgentOccupation(993385, "Nutricionista clínico"),
            new AgentOccupation(993390, "Educador físico"),
            new AgentOccupation(993395, "Personal trainer"),
            new AgentOccupation(993400, "Preparador físico"),
            new AgentOccupation(993405, "Técnico esportivo"),
            new AgentOccupation(993410, "Arbitro esportivo"),
            new AgentOccupation(993415, "Dirigente esportivo"),
            new AgentOccupation(993420, "Gestor esportivo"),
            new AgentOccupation(993425, "Consultor esportivo"),
            new AgentOccupation(993430, "Agente esportivo"),
            new AgentOccupation(993435, "Analista de desempenho esportivo"),
            new AgentOccupation(993440, "Scout esportivo"),
            new AgentOccupation(993445, "Jornalista esportivo"),
            new AgentOccupation(993450, "Comentarista esportivo"),
            new AgentOccupation(993455, "Narrador esportivo"),
            new AgentOccupation(993460, "Repórter esportivo"),
            new AgentOccupation(993465, "Produtor de eventos esportivos"),
            new AgentOccupation(993470, "Organizador de eventos esportivos"),
            new AgentOccupation(993475, "Especialista em marketing esportivo"),
            new AgentOccupation(993480, "Consultor de marketing esportivo"),
            new AgentOccupation(993485, "Especialista em patrocínios esportivos"),
            new AgentOccupation(993490, "Especialista em direito esportivo"),
            new AgentOccupation(993495, "Advogado esportivo"),
            new AgentOccupation(993500, "Procurador esportivo"),
            new AgentOccupation(993505, "Agente de atletas"),
            new AgentOccupation(993510, "Consultor de carreiras esportivas"),
            new AgentOccupation(993515, "Gestor de carreiras esportivas"),
            new AgentOccupation(993520, "Especialista em treinamento desportivo"),
            new AgentOccupation(993525, "Especialista em fisiologia do exercício"),
            new AgentOccupation(993530, "Especialista em biomecânica"),
            new AgentOccupation(993535, "Especialista em psicologia do esporte"),
            new AgentOccupation(993540, "Especialista em nutrição esportiva"),
            new AgentOccupation(993545, "Consultor de performance esportiva"),
            new AgentOccupation(993550, "Consultor de saúde e bem-estar"),
            new AgentOccupation(993555, "Consultor de qualidade de vida"),
            new AgentOccupation(993560, "Coach de vida"),
            new AgentOccupation(993565, "Coach de carreira"),
            new AgentOccupation(993570, "Coach executivo"),
            new AgentOccupation(993575, "Mentor"),
            new AgentOccupation(993580, "Especialista em desenvolvimento humano"),
            new AgentOccupation(993585, "Especialista em desenvolvimento organizacional"),
            new AgentOccupation(993590, "Consultor de recursos humanos"),
            new AgentOccupation(993595, "Analista de desenvolvimento humano"),
            new AgentOccupation(993600, "Gestor de desenvolvimento humano"),
            new AgentOccupation(993605, "Analista de treinamento e desenvolvimento"),
            new AgentOccupation(993610, "Gestor de treinamento e desenvolvimento"),
            new AgentOccupation(993615, "Especialista em educação corporativa"),
            new AgentOccupation(993620, "Consultor de educação corporativa"),
            new AgentOccupation(993625, "Instrutor corporativo"),
            new AgentOccupation(993630, "Facilitador"),
            new AgentOccupation(993635, "Mediador"),
            new AgentOccupation(993640, "Consultor de aprendizagem organizacional"),
            new AgentOccupation(993645, "Especialista em gestão do conhecimento"),
            new AgentOccupation(993650, "Especialista em aprendizagem organizacional"),
            new AgentOccupation(993655, "Consultor de inovação e criatividade"),
            new AgentOccupation(993660, "Consultor de mudanças organizacionais"),
            new AgentOccupation(993665, "Especialista em gestão de mudanças"),
            new AgentOccupation(993670, "Consultor de comunicação interna"),
            new AgentOccupation(993675, "Analista de comunicação interna"),
            new AgentOccupation(993680, "Gestor de comunicação interna"),
            new AgentOccupation(993685, "Consultor de cultura organizacional"),
            new AgentOccupation(993690, "Especialista em cultura organizacional"),
            new AgentOccupation(993695, "Consultor de liderança"),
            new AgentOccupation(993700, "Especialista em liderança"),
            new AgentOccupation(993705, "Consultor de coaching"),
            new AgentOccupation(993710, "Especialista em coaching"),
            new AgentOccupation(993715, "Mentor de liderança"),
            new AgentOccupation(993720, "Consultor de estratégias de liderança"),
            new AgentOccupation(993725, "Especialista em desenvolvimento de líderes"),
            new AgentOccupation(993730, "Consultor de performance organizacional"),
            new AgentOccupation(993735, "Analista de performance organizacional"),
            new AgentOccupation(993740, "Gestor de performance organizacional"),
            new AgentOccupation(993745, "Especialista em eficiência organizacional"),
            new AgentOccupation(993750, "Consultor de eficiência organizacional"),
            new AgentOccupation(993755, "Especialista em gestão de talentos"),
            new AgentOccupation(993760, "Consultor de gestão de talentos"),
            new AgentOccupation(993765, "Analista de gestão de talentos"),
            new AgentOccupation(993770, "Gestor de gestão de talentos"),
            new AgentOccupation(993775, "Especialista em aquisição de talentos"),
            new AgentOccupation(993780, "Consultor de aquisição de talentos"),
            new AgentOccupation(993785, "Analista de aquisição de talentos"),
            new AgentOccupation(993790, "Gestor de aquisição de talentos"),
            new AgentOccupation(993795, "Especialista em retenção de talentos"),
            new AgentOccupation(993800, "Consultor de retenção de talentos"),
            new AgentOccupation(993805, "Analista de retenção de talentos"),
            new AgentOccupation(993810, "Gestor de retenção de talentos"),
            new AgentOccupation(993815, "Especialista em desenvolvimento de talentos"),
            new AgentOccupation(993820, "Consultor de desenvolvimento de talentos"),
            new AgentOccupation(993825, "Analista de desenvolvimento de talentos"),
            new AgentOccupation(993830, "Gestor de desenvolvimento de talentos"),
            new AgentOccupation(993835, "Especialista em planejamento de carreira"),
            new AgentOccupation(993840, "Consultor de planejamento de carreira"),
            new AgentOccupation(993845, "Analista de planejamento de carreira"),
            new AgentOccupation(993850, "Gestor de planejamento de carreira"),
            new AgentOccupation(993855, "Especialista em sucessão de liderança"),
            new AgentOccupation(993860, "Consultor de sucessão de liderança"),
            new AgentOccupation(993865, "Analista de sucessão de liderança"),
            new AgentOccupation(993870, "Gestor de sucessão de liderança"),
            new AgentOccupation(993875, "Especialista em gestão de desempenho"),
            new AgentOccupation(993880, "Consultor de gestão de desempenho"),
            new AgentOccupation(993885, "Analista de gestão de desempenho"),
            new AgentOccupation(993890, "Gestor de gestão de desempenho"),
            new AgentOccupation(993895, "Especialista em gestão de competências"),
            new AgentOccupation(993900, "Consultor de gestão de competências"),
            new AgentOccupation(993905, "Analista de gestão de competências"),
            new AgentOccupation(993910, "Gestor de gestão de competências"),
            new AgentOccupation(993915, "Especialista em diversidade e inclusão"),
            new AgentOccupation(993920, "Consultor de diversidade e inclusão"),
            new AgentOccupation(993925, "Analista de diversidade e inclusão"),
            new AgentOccupation(993930, "Gestor de diversidade e inclusão"),
            new AgentOccupation(993935, "Especialista em bem-estar corporativo"),
            new AgentOccupation(993940, "Consultor de bem-estar corporativo"),
            new AgentOccupation(993945, "Analista de bem-estar corporativo"),
            new AgentOccupation(993950, "Gestor de bem-estar corporativo"),
            new AgentOccupation(993955, "Especialista em saúde ocupacional"),
            new AgentOccupation(993960, "Consultor de saúde ocupacional"),
            new AgentOccupation(993965, "Analista de saúde ocupacional"),
            new AgentOccupation(993970, "Gestor de saúde ocupacional"),
            new AgentOccupation(993975, "Especialista em ergonomia"),
            new AgentOccupation(993980, "Consultor de ergonomia"),
            new AgentOccupation(993985, "Analista de ergonomia"),
            new AgentOccupation(993990, "Gestor de ergonomia"),
            new AgentOccupation(993995, "Especialista em segurança psicossocial"),
            new AgentOccupation(994000, "Consultor de segurança psicossocial"),
            new AgentOccupation(994005, "Analista de segurança psicossocial"),
            new AgentOccupation(994010, "Gestor de segurança psicossocial"),
            new AgentOccupation(994015, "Especialista em segurança comportamental"),
            new AgentOccupation(994020, "Consultor de segurança comportamental"),
            new AgentOccupation(994025, "Analista de segurança comportamental"),
            new AgentOccupation(994030, "Gestor de segurança comportamental"),
            new AgentOccupation(994035, "Especialista em segurança emocional"),
            new AgentOccupation(994040, "Consultor de segurança emocional"),
            new AgentOccupation(994045, "Analista de segurança emocional"),
            new AgentOccupation(994050, "Gestor de segurança emocional"),
            new AgentOccupation(994055, "Especialista em saúde mental"),
            new AgentOccupation(994060, "Consultor de saúde mental"),
            new AgentOccupation(994065, "Analista de saúde mental"),
            new AgentOccupation(994070, "Gestor de saúde mental"),
            new AgentOccupation(994075, "Especialista em políticas de saúde"),
            new AgentOccupation(994080, "Consultor de políticas de saúde"),
            new AgentOccupation(994085, "Analista de políticas de saúde"),
            new AgentOccupation(994090, "Gestor de políticas de saúde"),
            new AgentOccupation(994095, "Especialista em promoção da saúde"),
            new AgentOccupation(994100, "Consultor de promoção da saúde"),
            new AgentOccupation(994105, "Analista de promoção da saúde"),
            new AgentOccupation(994110, "Gestor de promoção da saúde"),
            new AgentOccupation(994115, "Especialista em medicina preventiva"),
            new AgentOccupation(994120, "Consultor de medicina preventiva"),
            new AgentOccupation(994125, "Analista de medicina preventiva"),
            new AgentOccupation(994130, "Gestor de medicina preventiva"),
            new AgentOccupation(994135, "Especialista em epidemiologia"),
            new AgentOccupation(994140, "Consultor de epidemiologia"),
            new AgentOccupation(994145, "Analista de epidemiologia"),
            new AgentOccupation(994150, "Gestor de epidemiologia"),
            new AgentOccupation(994155, "Especialista em saúde pública"),
            new AgentOccupation(994160, "Consultor de saúde pública"),
            new AgentOccupation(994165, "Analista de saúde pública"),
            new AgentOccupation(994170, "Gestor de saúde pública"),
            new AgentOccupation(994175, "Especialista em vigilância sanitária"),
            new AgentOccupation(994180, "Consultor de vigilância sanitária"),
            new AgentOccupation(994185, "Analista de vigilância sanitária"),
            new AgentOccupation(994190, "Gestor de vigilância sanitária"),
            new AgentOccupation(994195, "Especialista em controle de infecções"),
            new AgentOccupation(994200, "Consultor de controle de infecções"),
            new AgentOccupation(994205, "Analista de controle de infecções"),
            new AgentOccupation(994210, "Gestor de controle de infecções"),
            new AgentOccupation(994215, "Especialista em biovigilância"),
            new AgentOccupation(994220, "Consultor de biovigilância"),
            new AgentOccupation(994225, "Analista de biovigilância"),
            new AgentOccupation(994230, "Gestor de biovigilância"),
            new AgentOccupation(994235, "Especialista em farmacovigilância"),
            new AgentOccupation(994240, "Consultor de farmacovigilância"),
            new AgentOccupation(994245, "Analista de farmacovigilância"),
            new AgentOccupation(994250, "Gestor de farmacovigilância"),
            new AgentOccupation(994255, "Especialista em hemovigilância"),
            new AgentOccupation(994260, "Consultor de hemovigilância"),
            new AgentOccupation(994265, "Analista de hemovigilância"),
            new AgentOccupation(994270, "Gestor de hemovigilância"),
            new AgentOccupation(994275, "Especialista em tecnovigilância"),
            new AgentOccupation(994280, "Consultor de tecnovigilância"),
            new AgentOccupation(994285, "Analista de tecnovigilância"),
            new AgentOccupation(994290, "Gestor de tecnovigilância"),
            new AgentOccupation(994295, "Especialista em saúde ocupacional"),
            new AgentOccupation(994300, "Consultor de saúde ocupacional"),
            new AgentOccupation(994305, "Analista de saúde ocupacional"),
            new AgentOccupation(994310, "Gestor de saúde ocupacional"),
            new AgentOccupation(994315, "Especialista em promoção da saúde"),
            new AgentOccupation(994320, "Consultor de promoção da saúde"),
            new AgentOccupation(994325, "Analista de promoção da saúde"),
            new AgentOccupation(994330, "Gestor de promoção da saúde"),
            new AgentOccupation(994335, "Especialista em saúde mental"),
            new AgentOccupation(994340, "Consultor de saúde mental"),
            new AgentOccupation(994345, "Analista de saúde mental"),
            new AgentOccupation(994350, "Gestor de saúde mental"),
            new AgentOccupation(994355, "Especialista em saúde emocional"),
            new AgentOccupation(994360, "Consultor de saúde emocional"),
            new AgentOccupation(994365, "Analista de saúde emocional"),
            new AgentOccupation(994370, "Gestor de saúde emocional"),
            new AgentOccupation(994375, "Especialista em saúde comportamental"),
            new AgentOccupation(994380, "Consultor de saúde comportamental"),
            new AgentOccupation(994385, "Analista de saúde comportamental"),
            new AgentOccupation(994390, "Gestor de saúde comportamental"),
            new AgentOccupation(994395, "Especialista em saúde física"),
            new AgentOccupation(994400, "Consultor de saúde física"),
            new AgentOccupation(994405, "Analista de saúde física"),
            new AgentOccupation(994410, "Gestor de saúde física"),
            new AgentOccupation(994415, "Especialista em ergonomia"),
            new AgentOccupation(994420, "Consultor de ergonomia"),
            new AgentOccupation(994425, "Analista de ergonomia"),
            new AgentOccupation(994430, "Gestor de ergonomia"),
            new AgentOccupation(994435, "Especialista em segurança emocional"),
            new AgentOccupation(994440, "Consultor de segurança emocional"),
            new AgentOccupation(994445, "Analista de segurança emocional"),
            new AgentOccupation(994450, "Gestor de segurança emocional"),
            new AgentOccupation(994455, "Especialista em segurança comportamental"),
            new AgentOccupation(994460, "Consultor de segurança comportamental"),
            new AgentOccupation(994465, "Analista de segurança comportamental"),
            new AgentOccupation(994470, "Gestor de segurança comportamental"),
            new AgentOccupation(994475, "Especialista em segurança psicossocial"),
            new AgentOccupation(994480, "Consultor de segurança psicossocial"),
            new AgentOccupation(994485, "Analista de segurança psicossocial"),
            new AgentOccupation(994490, "Gestor de segurança psicossocial"),
            new AgentOccupation(994495, "Especialista em controle de infecções"),
            new AgentOccupation(994500, "Consultor de controle de infecções"),
            new AgentOccupation(994505, "Analista de controle de infecções"),
            new AgentOccupation(994510, "Gestor de controle de infecções"),
            new AgentOccupation(994515, "Especialista em vigilância sanitária"),
            new AgentOccupation(994520, "Consultor de vigilância sanitária"),
            new AgentOccupation(994525, "Analista de vigilância sanitária"),
            new AgentOccupation(994530, "Gestor de vigilância sanitária"),
            new AgentOccupation(994535, "Especialista em biovigilância"),
            new AgentOccupation(994540, "Consultor de biovigilância"),
            new AgentOccupation(994545, "Analista de biovigilância"),
            new AgentOccupation(994550, "Gestor de biovigilância"),
            new AgentOccupation(994555, "Especialista em farmacovigilância"),
            new AgentOccupation(994560, "Consultor de farmacovigilância"),
            new AgentOccupation(994565, "Analista de farmacovigilância"),
            new AgentOccupation(994570, "Gestor de farmacovigilância"),
            new AgentOccupation(994575, "Especialista em hemovigilância"),
            new AgentOccupation(994580, "Consultor de hemovigilância"),
            new AgentOccupation(994585, "Analista de hemovigilância"),
            new AgentOccupation(994590, "Gestor de hemovigilância"),
            new AgentOccupation(994595, "Especialista em tecnovigilância"),
            new AgentOccupation(994600, "Consultor de tecnovigilância"),
            new AgentOccupation(994605, "Analista de tecnovigilância"),
            new AgentOccupation(994610, "Gestor de tecnovigilância"),
            new AgentOccupation(994615, "Especialista em epidemiologia"),
            new AgentOccupation(994620, "Consultor de epidemiologia"),
            new AgentOccupation(994625, "Analista de epidemiologia"),
            new AgentOccupation(994630, "Gestor de epidemiologia"),
            new AgentOccupation(994635, "Especialista em saúde pública"),
            new AgentOccupation(994640, "Consultor de saúde pública"),
            new AgentOccupation(994645, "Analista de saúde pública"),
            new AgentOccupation(994650, "Gestor de saúde pública"),
            new AgentOccupation(994655, "Especialista em saúde ocupacional"),
            new AgentOccupation(994660, "Consultor de saúde ocupacional"),
            new AgentOccupation(994665, "Analista de saúde ocupacional"),
            new AgentOccupation(994670, "Gestor de saúde ocupacional"),
            new AgentOccupation(994675, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994680, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994685, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994690, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994695, "Especialista em políticas de saúde"),
            new AgentOccupation(994700, "Consultor de políticas de saúde"),
            new AgentOccupation(994705, "Analista de políticas de saúde"),
            new AgentOccupation(994710, "Gestor de políticas de saúde"),
            new AgentOccupation(994715, "Especialista em medicina preventiva"),
            new AgentOccupation(994720, "Consultor de medicina preventiva"),
            new AgentOccupation(994725, "Analista de medicina preventiva"),
            new AgentOccupation(994730, "Gestor de medicina preventiva"),
            new AgentOccupation(994735, "Especialista em promoção da saúde"),
            new AgentOccupation(994740, "Consultor de promoção da saúde"),
            new AgentOccupation(994745, "Analista de promoção da saúde"),
            new AgentOccupation(994750, "Gestor de promoção da saúde"),
            new AgentOccupation(994755, "Especialista em vigilância sanitária"),
            new AgentOccupation(994760, "Consultor de vigilância sanitária"),
            new AgentOccupation(994765, "Analista de vigilância sanitária"),
            new AgentOccupation(994770, "Gestor de vigilância sanitária"),
            new AgentOccupation(994775, "Especialista em controle de infecções"),
            new AgentOccupation(994780, "Consultor de controle de infecções"),
            new AgentOccupation(994785, "Analista de controle de infecções"),
            new AgentOccupation(994790, "Gestor de controle de infecções"),
            new AgentOccupation(994795, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994800, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994805, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994810, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994815, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994820, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994825, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994830, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994835, "Especialista em vigilância sanitária"),
            new AgentOccupation(994840, "Consultor de vigilância sanitária"),
            new AgentOccupation(994845, "Analista de vigilância sanitária"),
            new AgentOccupation(994850, "Gestor de vigilância sanitária"),
            new AgentOccupation(994855, "Especialista em vigilância sanitária"),
            new AgentOccupation(994860, "Consultor de vigilância sanitária"),
            new AgentOccupation(994865, "Analista de vigilância sanitária"),
            new AgentOccupation(994870, "Gestor de vigilância sanitária"),
            new AgentOccupation(994875, "Especialista em vigilância sanitária"),
            new AgentOccupation(994880, "Consultor de vigilância sanitária"),
            new AgentOccupation(994885, "Analista de vigilância sanitária"),
            new AgentOccupation(994890, "Gestor de vigilância sanitária"),
            new AgentOccupation(994895, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994900, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994905, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994910, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994915, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994920, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994925, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994930, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994935, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(994940, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(994945, "Analista de vigilância epidemiológica"),
            new AgentOccupation(994950, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(994955, "Especialista em vigilância sanitária"),
            new AgentOccupation(994960, "Consultor de vigilância sanitária"),
            new AgentOccupation(994965, "Analista de vigilância sanitária"),
            new AgentOccupation(994970, "Gestor de vigilância sanitária"),
            new AgentOccupation(994975, "Especialista em vigilância sanitária"),
            new AgentOccupation(994980, "Consultor de vigilância sanitária"),
            new AgentOccupation(994985, "Analista de vigilância sanitária"),
            new AgentOccupation(994990, "Gestor de vigilância sanitária"),
            new AgentOccupation(994995, "Especialista em vigilância sanitária"),
            new AgentOccupation(995000, "Consultor de vigilância sanitária"),
            new AgentOccupation(995005, "Analista de vigilância sanitária"),
            new AgentOccupation(995010, "Gestor de vigilância sanitária"),
            new AgentOccupation(995015, "Especialista em vigilância sanitária"),
            new AgentOccupation(995020, "Consultor de vigilância sanitária"),
            new AgentOccupation(995025, "Analista de vigilância sanitária"),
            new AgentOccupation(995030, "Gestor de vigilância sanitária"),
            new AgentOccupation(995035, "Especialista em vigilância sanitária"),
            new AgentOccupation(995040, "Consultor de vigilância sanitária"),
            new AgentOccupation(995045, "Analista de vigilância sanitária"),
            new AgentOccupation(995050, "Gestor de vigilância sanitária"),
            new AgentOccupation(995055, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(995060, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(995065, "Analista de vigilância epidemiológica"),
            new AgentOccupation(995070, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(995075, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(995080, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(995085, "Analista de vigilância epidemiológica"),
            new AgentOccupation(995090, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(995095, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(995100, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(995105, "Analista de vigilância epidemiológica"),
            new AgentOccupation(995110, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(995115, "Especialista em vigilância sanitária"),
            new AgentOccupation(995120, "Consultor de vigilância sanitária"),
            new AgentOccupation(995125, "Analista de vigilância sanitária"),
            new AgentOccupation(995130, "Gestor de vigilância sanitária"),
            new AgentOccupation(995135, "Especialista em vigilância sanitária"),
            new AgentOccupation(995140, "Consultor de vigilância sanitária"),
            new AgentOccupation(995145, "Analista de vigilância sanitária"),
            new AgentOccupation(995150, "Gestor de vigilância sanitária"),
            new AgentOccupation(995155, "Especialista em vigilância sanitária"),
            new AgentOccupation(995160, "Consultor de vigilância sanitária"),
            new AgentOccupation(995165, "Analista de vigilância sanitária"),
            new AgentOccupation(995170, "Gestor de vigilância sanitária"),
            new AgentOccupation(995175, "Especialista em vigilância sanitária"),
            new AgentOccupation(995180, "Consultor de vigilância sanitária"),
            new AgentOccupation(995185, "Analista de vigilância sanitária"),
            new AgentOccupation(995190, "Gestor de vigilância sanitária"),
            new AgentOccupation(995195, "Especialista em vigilância sanitária"),
            new AgentOccupation(995200, "Consultor de vigilância sanitária"),
            new AgentOccupation(995205, "Analista de vigilância sanitária"),
            new AgentOccupation(995210, "Gestor de vigilância sanitária"),
            new AgentOccupation(995215, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(995220, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(995225, "Analista de vigilância epidemiológica"),
            new AgentOccupation(995230, "Gestor de vigilância epidemiológica"),
            new AgentOccupation(995235, "Especialista em vigilância epidemiológica"),
            new AgentOccupation(995240, "Consultor de vigilância epidemiológica"),
            new AgentOccupation(995245, "Analista de vigilância epidemiológica"),
            new AgentOccupation(995250, "Gestor de vigilância epidemiológica")
        };
    }
}
